equities_test=['A', 'ABBV', 'ADBE', 'ADS', 'AES', 'AIG', 'AKAM', 'ALL', 'AMD', 'AMP', 'ANSS', 'APA', 'ARE', 'AVGO',
               'AYI', 'BAX', 'BDX', 'BHGE', 'BLL', 'BWA', 'CAG', 'CBG', 'CCL', 'CF', 'CHRW', 'CL', 'CME', 'CNC', 'COL',
               'COTY', 'CSRA', 'CTSH', 'CXO', 'DFS', 'DHR', 'DISH', 'DOV', 'DTE', 'DWDP', 'ECL', 'EL', 'EQIX', 'ESRX',
               'ETR', 'EXPD', 'FAST', 'FDX', 'FISV', 'FLR', 'FOXA', 'GD', 'GIS', 'GOOGL', 'GRMN', 'HAL', 'HCA', 'HES',
               'HOLX', 'HPQ', 'HSIC', 'IBM', 'ILMN', 'INTU', 'IRM', 'IVZ', 'JNJ', 'K', 'KLAC', 'KO', 'KSU', 'LEN', 'LLY',
               'LOW', 'LYB', 'MAC', 'MCD', 'MDLZ', 'MHK', 'MMM', 'MOS', 'MS', 'MTD', 'NBL', 'NEM', 'NKE', 'NRG', 'NUE',
               'NWSA', 'ORCL', 'PBCT', 'PDCO', 'PFG', 'PHM', 'PM', 'PPG', 'PSA', 'PX', 'QCOM', 'REG', 'RHT', 'ROK',
               'RSG', 'SCG', 'SIG', 'SNA', 'SPG', 'STI', 'SWK', 'SYMC', 'TDG', 'TJX', 'TRIP', 'TSN', 'TXT', 'UDR',
               'UNM', 'USB', 'VFC', 'VNO', 'VTR', 'WDC', 'WLTW', 'WRK', 'WYNN', 'XLNX', 'XYL', 'ZTS']

equitties_train=['AAL', 'AAP', 'AAPL', 'ABC', 'ABT', 'ACN', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE', 'AEP', 'AET', 'AFL',
                 'AGN', 'AIV', 'AIZ', 'AJG', 'ALB', 'ALGN', 'ALK', 'ALLE', 'ALXN', 'AMAT', 'AME', 'AMG', 'AMGN', 'AMT',
                 'AMZN', 'ANDV', 'ANTM', 'AON', 'AOS', 'APC', 'APD', 'APH', 'ARNC', 'ATVI', 'AVB', 'AVY', 'AWK', 'AXP',
                 'AZO', 'BA', 'BAC', 'BBT', 'BBY', 'BCR', 'BEN', 'BHF', 'BIIB', 'BK', 'BLK', 'BMY',
                 'BSX', 'BXP', 'C', 'CA', 'CAH', 'CAT', 'CB', 'CBOE', 'CBS', 'CCI', 'CDNS', 'CELG', 'CERN', 'CFG',
                 'CHD', 'CHK', 'CHTR', 'CI', 'CINF', 'CLX', 'CMA', 'CMCSA', 'CMG', 'CMI', 'CMS', 'CNP', 'COF', 'COG',
                 'COO', 'COP', 'COST', 'CPB', 'CRM', 'CSCO', 'CSX', 'CTAS', 'CTL', 'CTXS', 'CVS', 'CVX', 'D', 'DAL',
                 'DE', 'DG', 'DGX', 'DHI', 'DIS', 'DISCA', 'DISCK', 'DLPH', 'DLR', 'DLTR', 'DPS', 'DRE', 'DRI', 'DUK',
                 'DVA', 'DVN', 'DXC', 'EA', 'EBAY', 'ED', 'EFX', 'EIX', 'EMN', 'EMR', 'EOG', 'EQR', 'EQT', 'ES', 'ESS',
                 'ETFC', 'ETN', 'EVHC', 'EW', 'EXC', 'EXPE', 'EXR', 'F', 'FB', 'FBHS', 'FCX', 'FE', 'FFIV', 'FIS',
                 'FITB', 'FL', 'FLIR', 'FLS', 'FMC', 'FOX', 'FRT', 'FTI', 'FTV', 'GE', 'GGP', 'GILD', 'GLW', 'GM',
                 'GOOG', 'GPC', 'GPN', 'GPS', 'GS', 'GT', 'GWW', 'HAS', 'HBAN', 'HBI', 'HCN', 'HCP', 'HD', 'HIG',
                 'HLT', 'HOG', 'HON', 'HP', 'HPE', 'HRB', 'HRL', 'HRS', 'HST', 'HSY', 'HUM', 'ICE', 'IDXX', 'IFF',
                 'INCY', 'INFO', 'INTC', 'IP', 'IPG', 'IR', 'ISRG', 'IT', 'ITW', 'JBHT', 'JCI', 'JEC', 'JNPR', 'JPM',
                 'JWN', 'KEY', 'KHC', 'KIM', 'KMB', 'KMI', 'KMX', 'KORS', 'KR', 'KSS', 'L', 'LB', 'LEG', 'LH', 'LKQ',
                 'LLL', 'LMT', 'LNC', 'LNT', 'LRCX', 'LUK', 'LUV', 'M', 'MA', 'MAA', 'MAR', 'MAS', 'MAT', 'MCHP', 'MCK',
                 'MCO', 'MDT', 'MET', 'MGM', 'MKC', 'MLM', 'MMC', 'MNST', 'MO', 'MON', 'MPC', 'MRK', 'MRO', 'MSFT',
                 'MSI', 'MTB', 'MU', 'MYL', 'NAVI', 'NCLH', 'NDAQ', 'NEE', 'NFLX', 'NFX', 'NI', 'NLSN', 'NOC', 'NOV',
                 'NSC', 'NTAP', 'NTRS', 'NVDA', 'NWL', 'NWS', 'O', 'OKE', 'OMC', 'ORLY', 'OXY', 'PAYX', 'PCAR', 'PCG',
                 'PCLN', 'PEG', 'PEP', 'PFE', 'PG', 'PGR', 'PH', 'PKG', 'PKI', 'PLD', 'PNC', 'PNR', 'PNW', 'PPL',
                 'PRGO', 'PRU', 'PSX', 'PVH', 'PWR', 'PXD', 'PYPL', 'Q', 'QRVO', 'RCL', 'RE', 'REGN', 'RF', 'RHI',
                 'RJF', 'RL', 'RMD', 'ROP', 'ROST', 'RRC', 'RTN', 'SBAC', 'SBUX', 'SCHW', 'SEE', 'SHW', 'SJM', 'SLB',
                 'SLG', 'SNI', 'SNPS', 'SO', 'SPGI', 'SRCL', 'SRE', 'STT', 'STX', 'STZ', 'SWKS', 'SYF', 'SYK', 'SYY',
                 'T', 'TAP', 'TEL', 'TGT', 'TIF', 'TMK', 'TMO', 'TPR', 'TROW', 'TRV', 'TSCO', 'TSS', 'TWX', 'TXN', 'UA',
                 'UAA', 'UAL', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'UTX', 'V', 'VAR', 'VIAB', 'VLO', 'VMC',
                 'VRSK', 'VRSN', 'VRTX', 'VZ', 'WAT', 'WBA', 'WEC', 'WFC', 'WHR', 'WM', 'WMB', 'WMT', 'WU', 'WY', 'WYN',
                 'XEC', 'XEL', 'XL', 'XOM', 'XRAY', 'XRX', 'YUM', 'ZBH', 'ZION']
equities_other=['BF.B', 'BRK.B']
equities_done=['AAL','AAP','AAPL','ABC','ABT','ACN','ADI','ADM','ADP','ADSK','AEE','AEP','AET','AFL','AGN','AIV','AIZ','AJG',
                'ALB','ALGN','ALK','ALLE','ALXN','AME','AMG','AMAT','AMT','AMGN','AMZN','ANDV','ANTM','APC','AOS','AON','APH',
               'APD','ARNC','ATVI','AVB','AVY','AWK','AXP','AZO','BA','BAC','BBT','BBY','BEN','BCR','BHF','BK','BLK','BIIB','BMY',
               'CMA','DLPH','KORS','WU','ZTS']

